"""
mixtures.py

Defines a registry of dataset mixtures and weights for the Open-X Embodiment Datasets. Each dataset is associated with
a float "sampling weight"
"""

from typing import Dict, List, Tuple


# Dataset mixture name mapped to a list of tuples containing:
## {nakename: [(data_name, sampling_weight, robot_type)] }
DATASET_NAMED_MIXTURES = {

    "custom_dataset": [
        ("custom_dataset_name", 1.0, "custom_robot_config"),
    ],
    "custom_dataset_2": [
        ("custom_dataset_name_1", 1.0, "custom_robot_config"),
        ("custom_dataset_name_2", 1.0, "custom_robot_config"),
    ],

    "libero_all": [
        ("libero_object_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_goal_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_spatial_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        ("libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
                # ("libero_90_no_noops_lerobot", 1.0, "libero_franka"),
    ],
    "bridge": [
        ("bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
    ],
    "bridge_rt_1": [
        ("bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
        ("fractal20220817_data_0.1.0_lerobot", 1.0, "oxe_rt1"),
    ],
    "calvin_task_ABC_D": [
        ("calvin_abc_d_1.0.0_lerobot", 1.0, "libero_franka"),
    ],
    "calvin_task_D_D": [
        ("calvin_d_d_1.0.0_lerobot", 1.0, "libero_franka"),
    ],

    "demo_sim_pick_place": [
        ("sim_pick_place", 1.0, "demo_sim_franka_delta_joints"),
    ],

    "custom_dataset": [
        ("custom_dataset_name", 1.0, "custom_robot_config"),
    ],
    "custom_dataset_2": [
        ("custom_dataset_name_1", 1.0, "custom_robot_config"),
        ("custom_dataset_name_2", 1.0, "custom_robot_config"),
    ],

    "fourier_gr1_unified_1000": [
        ("gr1_unified.PnPBottleToCabinetClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPCanToDrawerClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPCupToDrawerClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPMilkToMicrowaveClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPPotatoToMicrowaveClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PnPWineToCabinetClose_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToBasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToPanSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToPotSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromCuttingboardToTieredbasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToBasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToBowlSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlacematToTieredshelfSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToBowlSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToPanSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromPlateToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToCardboardboxSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToPlateSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToPotSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToTieredbasketSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
        ("gr1_unified.PosttrainPnPNovelFromTrayToTieredshelfSplitA_GR1ArmsAndWaistFourierHands_1000", 1.0, "fourier_gr1_arms_waist"),
    ],

    "BEHAVIOR_challenge": [
        ("BEHAVIOR_challenge", 1.0, "R1Pro"),
    ],


    "SO101_pick": [
        ("pick_dataset_name", 1.0, "SO101"),
    ],

    "arx_x5": [
        ("arx_x5", 1.0, "arx_x5"),
    ],

    "robotwin_all": [
        ("RoboTwin/Clean/adjust_bottle", 1.0, "robotwin"),
        ("RoboTwin/Clean/beat_block_hammer", 1.0, "robotwin"),
        ("RoboTwin/Clean/blocks_ranking_rgb", 1.0, "robotwin"),
        ("RoboTwin/Clean/blocks_ranking_size", 1.0, "robotwin"),
        ("RoboTwin/Clean/click_alarmclock", 1.0, "robotwin"),
        ("RoboTwin/Clean/click_bell", 1.0, "robotwin"),
        ("RoboTwin/Clean/dump_bin_bigbin", 1.0, "robotwin"),
        ("RoboTwin/Clean/grab_roller", 1.0, "robotwin"),
        ("RoboTwin/Clean/handover_block", 1.0, "robotwin"),
        ("RoboTwin/Clean/handover_mic", 1.0, "robotwin"),
        ("RoboTwin/Clean/hanging_mug", 1.0, "robotwin"),
        ("RoboTwin/Clean/lift_pot", 1.0, "robotwin"),
        ("RoboTwin/Clean/move_can_pot", 1.0, "robotwin"),
        ("RoboTwin/Clean/move_pillbottle_pad", 1.0, "robotwin"),
        ("RoboTwin/Clean/move_playingcard_away", 1.0, "robotwin"),
        ("RoboTwin/Clean/move_stapler_pad", 1.0, "robotwin"),
        ("RoboTwin/Clean/open_laptop", 1.0, "robotwin"),
        ("RoboTwin/Clean/open_microwave", 1.0, "robotwin"),
        ("RoboTwin/Clean/pick_diverse_bottles", 1.0, "robotwin"),
        ("RoboTwin/Clean/pick_dual_bottles", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_a2b_left", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_a2b_right", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_bread_basket", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_bread_skillet", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_burger_fries", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_can_basket", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_cans_plasticbox", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_container_plate", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_dual_shoes", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_empty_cup", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_fan", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_mouse_pad", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_object_basket", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_object_scale", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_object_stand", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_phone_stand", 1.0, "robotwin"),
        ("RoboTwin/Clean/place_shoe", 1.0, "robotwin"),
        ("RoboTwin/Clean/press_stapler", 1.0, "robotwin"),
        ("RoboTwin/Clean/put_bottles_dustbin", 1.0, "robotwin"),
        ("RoboTwin/Clean/put_object_cabinet", 1.0, "robotwin"),
        ("RoboTwin/Clean/rotate_qrcode", 1.0, "robotwin"),
        ("RoboTwin/Clean/scan_object", 1.0, "robotwin"),
        ("RoboTwin/Clean/shake_bottle", 1.0, "robotwin"),
        ("RoboTwin/Clean/shake_bottle_horizontally", 1.0, "robotwin"),
        ("RoboTwin/Clean/stack_blocks_three", 1.0, "robotwin"),
        ("RoboTwin/Clean/stack_blocks_two", 1.0, "robotwin"),
        ("RoboTwin/Clean/stack_bowls_three", 1.0, "robotwin"),
        ("RoboTwin/Clean/stack_bowls_two", 1.0, "robotwin"),
        ("RoboTwin/Clean/stamp_seal", 1.0, "robotwin"),
        ("RoboTwin/Clean/turn_switch", 1.0, "robotwin"),
        ("RoboTwin/Randomized/adjust_bottle", 1.0, "robotwin"),
        ("RoboTwin/Randomized/beat_block_hammer", 1.0, "robotwin"),
        ("RoboTwin/Randomized/blocks_ranking_rgb", 1.0, "robotwin"),
        ("RoboTwin/Randomized/blocks_ranking_size", 1.0, "robotwin"),
        ("RoboTwin/Randomized/click_alarmclock", 1.0, "robotwin"),
        ("RoboTwin/Randomized/click_bell", 1.0, "robotwin"),
        ("RoboTwin/Randomized/dump_bin_bigbin", 1.0, "robotwin"),
        ("RoboTwin/Randomized/grab_roller", 1.0, "robotwin"),
        ("RoboTwin/Randomized/handover_block", 1.0, "robotwin"),
        ("RoboTwin/Randomized/handover_mic", 1.0, "robotwin"),
        ("RoboTwin/Randomized/hanging_mug", 1.0, "robotwin"),
        ("RoboTwin/Randomized/lift_pot", 1.0, "robotwin"),
        ("RoboTwin/Randomized/move_can_pot", 1.0, "robotwin"),
        ("RoboTwin/Randomized/move_pillbottle_pad", 1.0, "robotwin"),
        ("RoboTwin/Randomized/move_playingcard_away", 1.0, "robotwin"),
        ("RoboTwin/Randomized/move_stapler_pad", 1.0, "robotwin"),
        ("RoboTwin/Randomized/open_laptop", 1.0, "robotwin"),
        ("RoboTwin/Randomized/open_microwave", 1.0, "robotwin"),
        ("RoboTwin/Randomized/pick_diverse_bottles", 1.0, "robotwin"),
        ("RoboTwin/Randomized/pick_dual_bottles", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_a2b_left", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_a2b_right", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_bread_basket", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_bread_skillet", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_burger_fries", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_can_basket", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_cans_plasticbox", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_container_plate", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_dual_shoes", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_empty_cup", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_fan", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_mouse_pad", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_object_basket", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_object_scale", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_object_stand", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_phone_stand", 1.0, "robotwin"),
        ("RoboTwin/Randomized/place_shoe", 1.0, "robotwin"),
        ("RoboTwin/Randomized/press_stapler", 1.0, "robotwin"),
        ("RoboTwin/Randomized/put_bottles_dustbin", 1.0, "robotwin"),
        ("RoboTwin/Randomized/put_object_cabinet", 1.0, "robotwin"),
        ("RoboTwin/Randomized/rotate_qrcode", 1.0, "robotwin"),
        ("RoboTwin/Randomized/scan_object", 1.0, "robotwin"),
        ("RoboTwin/Randomized/shake_bottle", 1.0, "robotwin"),
        ("RoboTwin/Randomized/shake_bottle_horizontally", 1.0, "robotwin"),
        ("RoboTwin/Randomized/stack_blocks_three", 1.0, "robotwin"),
        ("RoboTwin/Randomized/stack_blocks_two", 1.0, "robotwin"),
        ("RoboTwin/Randomized/stack_bowls_three", 1.0, "robotwin"),
        ("RoboTwin/Randomized/stack_bowls_two", 1.0, "robotwin"),
        ("RoboTwin/Randomized/stamp_seal", 1.0, "robotwin"),
        ("RoboTwin/Randomized/turn_switch", 1.0, "robotwin"),
    ],
    "robotwin_all_50": [
        ("RoboTwin/Clean/adjust_bottle", 1.0, "robotwin50"),
        ("RoboTwin/Clean/beat_block_hammer", 1.0, "robotwin50"),
        ("RoboTwin/Clean/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("RoboTwin/Clean/blocks_ranking_size", 1.0, "robotwin50"),
        ("RoboTwin/Clean/click_alarmclock", 1.0, "robotwin50"),
        ("RoboTwin/Clean/click_bell", 1.0, "robotwin50"),
        ("RoboTwin/Clean/dump_bin_bigbin", 1.0, "robotwin50"),
        ("RoboTwin/Clean/grab_roller", 1.0, "robotwin50"),
        ("RoboTwin/Clean/handover_block", 1.0, "robotwin50"),
        ("RoboTwin/Clean/handover_mic", 1.0, "robotwin50"),
        ("RoboTwin/Clean/hanging_mug", 1.0, "robotwin50"),
        ("RoboTwin/Clean/lift_pot", 1.0, "robotwin50"),
        ("RoboTwin/Clean/move_can_pot", 1.0, "robotwin50"),
        ("RoboTwin/Clean/move_pillbottle_pad", 1.0, "robotwin50"),
        ("RoboTwin/Clean/move_playingcard_away", 1.0, "robotwin50"),
        ("RoboTwin/Clean/move_stapler_pad", 1.0, "robotwin50"),
        ("RoboTwin/Clean/open_laptop", 1.0, "robotwin50"),
        ("RoboTwin/Clean/open_microwave", 1.0, "robotwin50"),
        ("RoboTwin/Clean/pick_diverse_bottles", 1.0, "robotwin50"),
        ("RoboTwin/Clean/pick_dual_bottles", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_a2b_left", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_a2b_right", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_bread_basket", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_bread_skillet", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_burger_fries", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_can_basket", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_cans_plasticbox", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_container_plate", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_dual_shoes", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_empty_cup", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_fan", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_mouse_pad", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_object_basket", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_object_scale", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_object_stand", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_phone_stand", 1.0, "robotwin50"),
        ("RoboTwin/Clean/place_shoe", 1.0, "robotwin50"),
        ("RoboTwin/Clean/press_stapler", 1.0, "robotwin50"),
        ("RoboTwin/Clean/put_bottles_dustbin", 1.0, "robotwin50"),
        ("RoboTwin/Clean/put_object_cabinet", 1.0, "robotwin50"),
        ("RoboTwin/Clean/rotate_qrcode", 1.0, "robotwin50"),
        ("RoboTwin/Clean/scan_object", 1.0, "robotwin50"),
        ("RoboTwin/Clean/shake_bottle", 1.0, "robotwin50"),
        ("RoboTwin/Clean/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("RoboTwin/Clean/stack_blocks_three", 1.0, "robotwin50"),
        ("RoboTwin/Clean/stack_blocks_two", 1.0, "robotwin50"),
        ("RoboTwin/Clean/stack_bowls_three", 1.0, "robotwin50"),
        ("RoboTwin/Clean/stack_bowls_two", 1.0, "robotwin50"),
        ("RoboTwin/Clean/stamp_seal", 1.0, "robotwin50"),
        ("RoboTwin/Clean/turn_switch", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/adjust_bottle", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/beat_block_hammer", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/blocks_ranking_rgb", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/blocks_ranking_size", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/click_alarmclock", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/click_bell", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/dump_bin_bigbin", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/grab_roller", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/handover_block", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/handover_mic", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/hanging_mug", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/lift_pot", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/move_can_pot", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/move_pillbottle_pad", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/move_playingcard_away", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/move_stapler_pad", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/open_laptop", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/open_microwave", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/pick_diverse_bottles", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/pick_dual_bottles", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_a2b_left", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_a2b_right", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_bread_basket", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_bread_skillet", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_burger_fries", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_can_basket", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_cans_plasticbox", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_container_plate", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_dual_shoes", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_empty_cup", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_fan", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_mouse_pad", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_object_basket", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_object_scale", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_object_stand", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_phone_stand", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/place_shoe", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/press_stapler", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/put_bottles_dustbin", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/put_object_cabinet", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/rotate_qrcode", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/scan_object", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/shake_bottle", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/shake_bottle_horizontally", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/stack_blocks_three", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/stack_blocks_two", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/stack_bowls_three", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/stack_bowls_two", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/stamp_seal", 1.0, "robotwin50"),
        ("RoboTwin/Randomized/turn_switch", 1.0, "robotwin50"),
    ],
    "robotwin": [
        ("adjust_bottle", 1.0, "robotwin"),
        ("beat_block_hammer", 1.0, "robotwin"),
        ("blocks_ranking_rgb", 1.0, "robotwin"),
        ("blocks_ranking_size", 1.0, "robotwin"),
        ("click_alarmclock", 1.0, "robotwin"),
        ("click_bell", 1.0, "robotwin"),
        ("dump_bin_bigbin", 1.0, "robotwin"),
        ("grab_roller", 1.0, "robotwin"),
        ("handover_block", 1.0, "robotwin"),
        ("handover_mic", 1.0, "robotwin"),
        ("hanging_mug", 1.0, "robotwin"),
        ("lift_pot", 1.0, "robotwin"),
        ("move_can_pot", 1.0, "robotwin"),
        ("move_pillbottle_pad", 1.0, "robotwin"),
        ("move_playingcard_away", 1.0, "robotwin"),
        ("move_stapler_pad", 1.0, "robotwin"),
        ("open_laptop", 1.0, "robotwin"),
        ("open_microwave", 1.0, "robotwin"),
        ("pick_diverse_bottles", 1.0, "robotwin"),
        ("pick_dual_bottles", 1.0, "robotwin"),
        ("place_a2b_left", 1.0, "robotwin"),
        ("place_a2b_right", 1.0, "robotwin"),
        ("place_bread_basket", 1.0, "robotwin"),
        ("place_bread_skillet", 1.0, "robotwin"),
        ("place_burger_fries", 1.0, "robotwin"),
        ("place_can_basket", 1.0, "robotwin"),
        ("place_cans_plasticbox", 1.0, "robotwin"),
        ("place_container_plate", 1.0, "robotwin"),
        ("place_dual_shoes", 1.0, "robotwin"),
        ("place_empty_cup", 1.0, "robotwin"),
        ("place_fan", 1.0, "robotwin"),
        ("place_mouse_pad", 1.0, "robotwin"),
        ("place_object_basket", 1.0, "robotwin"),
        ("place_object_scale", 1.0, "robotwin"),
        ("place_object_stand", 1.0, "robotwin"),
        ("place_phone_stand", 1.0, "robotwin"),
        ("place_shoe", 1.0, "robotwin"),
        ("press_stapler", 1.0, "robotwin"),
        ("put_bottles_dustbin", 1.0, "robotwin"),
        ("put_object_cabinet", 1.0, "robotwin"),
        ("rotate_qrcode", 1.0, "robotwin"),
        ("scan_object", 1.0, "robotwin"),
        ("shake_bottle", 1.0, "robotwin"),
        ("shake_bottle_horizontally", 1.0, "robotwin"),
        ("stack_blocks_three", 1.0, "robotwin"),
        ("stack_blocks_two", 1.0, "robotwin"),
        ("stack_bowls_three", 1.0, "robotwin"),
        ("stack_bowls_two", 1.0, "robotwin"),
        ("stamp_seal", 1.0, "robotwin"),
        ("turn_switch", 1.0, "robotwin"),
    ],

    "robotwin_task1": [
        ("adjust_bottle", 1.0, "robotwin"),
    ],
    "robotwin_task2": [
        ("place_a2b_left", 1.0, "robotwin"),
        ("place_a2b_right", 1.0, "robotwin"),
    ],

    "multi_robot": [
        ("LEROBOT_LIBERO_DATA/libero_10_no_noops_1.0.0_lerobot", 1.0, "libero_franka"),
        # ("OXE_LEROBOT_DATASET/bridge_orig_1.0.0_lerobot", 1.0, "oxe_bridge"),
    ],
}

DATASET_NAMED_MIXTURES["bridge_fractal_libero"] = (
    DATASET_NAMED_MIXTURES["bridge_rt_1"]
    + DATASET_NAMED_MIXTURES["libero_all"]
)

DATASET_NAMED_MIXTURES["bridge_fractal_libero_calvin"] = (
    DATASET_NAMED_MIXTURES["bridge_rt_1"]
    + DATASET_NAMED_MIXTURES["libero_all"]
    + DATASET_NAMED_MIXTURES["calvin_task_ABC_D"]
)

DATASET_NAMED_MIXTURES["bridge_fractal_libero_robotwin"] = (
    DATASET_NAMED_MIXTURES["bridge_rt_1"]
    + DATASET_NAMED_MIXTURES["libero_all"]
    + DATASET_NAMED_MIXTURES["robotwin_all"]
)
